import { notFound } from 'next/navigation';
import { cache } from 'react';
import type { Metadata } from 'next';
import { eq } from 'drizzle-orm';
import { getDb } from '@/lib/db';
import { replays, tags } from '@/lib/schema';
import { orderPlayersOwnerFirst } from '@/lib/players';
import { isSampleReplaySlug } from '@/lib/sampleReplays';
import { anonymizePlayersSummary } from '@/lib/anonymizeReplay';
import { auth } from '@/auth';
import { canViewAltPerspective, canViewReplayIdentities } from '@/lib/altPerspective';
import { verifyMoment } from '@/lib/shareToken';
import { ReplayViewer } from './ReplayViewer';

export const dynamic = 'force-dynamic';

interface PageProps {
  params: Promise<{ slug: string }>;
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}

// Cached per request render — generateMetadata + the page share ONE query.
const loadReplay = cache(async (slug: string) => {
  const [row] = await getDb().select().from(replays).where(eq(replays.slug, slug)).limit(1);
  return row ?? null;
});

// B113: per-frame Open Graph so a shared `?f=` link unfurls into the moment card
// (the image is generated by /api/replays/[slug]/og-image). Title = matchup; the
// optional `?t=` signed token surfaces a tag in the description; samples stay
// anonymized.
export async function generateMetadata({ params, searchParams }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const sp = await searchParams;
  const f = typeof sp.f === 'string' ? sp.f : undefined;
  const t = typeof sp.t === 'string' ? sp.t : undefined;

  const row = await loadReplay(slug);
  if (!row) return { title: 'KaraBuddy' };

  // B122: only the uploader / a teammate sees real karabast handles. Everyone
  // else (incl. anonymous link visitors + crawlers) gets the leader matchup. A
  // user-set displayName is always safe to show (it's user-chosen).
  const session = await auth();
  const viewerUserId = (session?.user as any)?.id ?? null;
  const anonymize = isSampleReplaySlug(slug)
    || !(await canViewReplayIdentities(row, { sessionUserId: viewerUserId, installToken: null }));
  const ordered = orderPlayersOwnerFirst(row.players, row.ownerPlayerId) as any[];
  const nameOf = (p: any) => (p?.username ?? 'Player') + (p?.leader?.name ? ` (${p.leader.name})` : '');
  const leaderMatchup = `${ordered[0]?.leader?.name ?? 'Unknown'} vs ${ordered[1]?.leader?.name ?? 'Unknown'}`;
  const matchup = (row as any).displayName
    ? (row as any).displayName
    : anonymize ? leaderMatchup : `${nameOf(ordered[0])} vs ${nameOf(ordered[1])}`;

  // Opt-in tag in the description (B113 signed token; never for samples, but OK
  // for an anonymized viewer — the sharer explicitly authorized this tag).
  let tagLine: string | null = null;
  if (t && !isSampleReplaySlug(slug)) {
    const frameIndex = Math.max(0, (parseInt(f || '1', 10) || 1) - 1);
    const claim = verifyMoment(t);
    if (claim && claim.slug === slug && claim.frameIndex === frameIndex) {
      const [tag] = await getDb().select().from(tags).where(eq(tags.id, claim.tagId)).limit(1);
      if (tag && tag.replaySlug === slug && tag.frameIndex === frameIndex && tag.comment) tagLine = tag.comment;
    }
  }
  const frameLabel = f ? `frame ${parseInt(f, 10) || 1}` : 'the start';
  const description = tagLine ? `“${tagLine.slice(0, 180)}”` : `${matchup} — Star Wars Unlimited replay at ${frameLabel}.`;
  const image = `/api/replays/${slug}/og-image?f=${encodeURIComponent(f ?? '')}&t=${encodeURIComponent(t ?? '')}`;

  return {
    title: `${matchup} · KaraBuddy`,
    description,
    openGraph: { title: matchup, description, type: 'website', images: [{ url: image, width: 1200, height: 630 }] },
    twitter: { card: 'summary_large_image', title: matchup, description, images: [image] },
  };
}

export default async function ReplayPage({ params }: PageProps) {
  const { slug } = await params;
  const row = await loadReplay(slug);
  if (!row) notFound();

  // Serialize timestamps for client transport. Owner-first player order
  // (B59-followup) so the sidebar matchup + default title both read
  // "<me> vs <them>" instead of being order-dependent on the raw jsonb
  // key sort.
  const players = orderPlayersOwnerFirst(row.players, row.ownerPlayerId);

  // B122: real karabast handles + deck lists are visible ONLY to the uploader
  // or a teammate of the uploader. Everyone else (anonymous link visitors, other
  // players) gets "Player N" handles, the leader-matchup title, and no full deck
  // lists (the viewer still derives "seen" cards from the frames). Curated SAMPLE
  // replays (B107) stay force-anonymized. Order is preserved so labels line up.
  const session = await auth();
  const viewerUserId = (session?.user as any)?.id ?? null;
  const anonymize = isSampleReplaySlug(slug)
    || !(await canViewReplayIdentities(row, { sessionUserId: viewerUserId, installToken: null }));

  // B112: Flip control only for a viewer entitled to the 2nd perspective.
  const canFlip = !anonymize && (await canViewAltPerspective(slug, viewerUserId));

  const replay = {
    ...row,
    createdAt: row.createdAt.toISOString(),
    players: anonymize ? anonymizePlayersSummary(players as any[]) : players,
    // A user-set title is always shown (it's user-chosen — never a leaked karabast
    // handle); only the AUTO default differs (leader matchup for anon viewers).
    // Full deck lists are dropped for unauthorized viewers (uploader/teammate-only)
    // — the DecksModal shows only the "seen" cards instead.
    displayName: (row as any).displayName,
    decks: anonymize ? null : (row as any).decks,
  };

  // B71: tags are no longer SSR'd — the viewer fetches them from
  // GET /api/replays/[slug]/tags so the server can scope them to the
  // viewer (own + team-scoped only). SSR'ing all tags would leak other
  // teams' / others' personal comments into the initial HTML.
  return <ReplayViewer replay={replay} initialTags={[]} anonymize={anonymize} canFlip={canFlip} />;
}
