import { notFound } from 'next/navigation';
import { cache } from 'react';
import type { Metadata } from 'next';
import { eq } from 'drizzle-orm';
import { getDb } from '@/lib/db';
import { replays, tags } from '@/lib/schema';
import { orderPlayersOwnerFirst } from '@/lib/players';
import { isSampleReplaySlug } from '@/lib/sampleReplays';
import { anonymizePlayersSummary } from '@/lib/anonymizeReplay';
import { auth } from '@/auth';
import { canViewAltPerspective } from '@/lib/altPerspective';
import { verifyMoment } from '@/lib/shareToken';
import { ReplayViewer } from './ReplayViewer';

export const dynamic = 'force-dynamic';

interface PageProps {
  params: Promise<{ slug: string }>;
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}

// Cached per request render — generateMetadata + the page share ONE query.
const loadReplay = cache(async (slug: string) => {
  const [row] = await getDb().select().from(replays).where(eq(replays.slug, slug)).limit(1);
  return row ?? null;
});

// B113: per-frame Open Graph so a shared `?f=` link unfurls into the moment card
// (the image is generated by /api/replays/[slug]/og-image). Title = matchup; the
// optional `?t=` signed token surfaces a tag in the description; samples stay
// anonymized.
export async function generateMetadata({ params, searchParams }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const sp = await searchParams;
  const f = typeof sp.f === 'string' ? sp.f : undefined;
  const t = typeof sp.t === 'string' ? sp.t : undefined;

  const row = await loadReplay(slug);
  if (!row) return { title: 'KaraBuddy' };

  const anonymize = isSampleReplaySlug(slug);
  const ordered = orderPlayersOwnerFirst(row.players, row.ownerPlayerId);
  const shown = (anonymize ? anonymizePlayersSummary(ordered as any[]) : ordered) as any[];
  const nameOf = (p: any) => (p?.username ?? 'Player') + (p?.leader?.name ? ` (${p.leader.name})` : '');
  const matchup = `${nameOf(shown[0])} vs ${nameOf(shown[1])}`;

  // Opt-in tag in the description (signed token; never for samples).
  let tagLine: string | null = null;
  if (t && !anonymize) {
    const frameIndex = Math.max(0, (parseInt(f || '1', 10) || 1) - 1);
    const claim = verifyMoment(t);
    if (claim && claim.slug === slug && claim.frameIndex === frameIndex) {
      const [tag] = await getDb().select().from(tags).where(eq(tags.id, claim.tagId)).limit(1);
      if (tag && tag.replaySlug === slug && tag.frameIndex === frameIndex && tag.comment) tagLine = tag.comment;
    }
  }
  const frameLabel = f ? `frame ${parseInt(f, 10) || 1}` : 'the start';
  const description = tagLine ? `“${tagLine.slice(0, 180)}”` : `${matchup} — Star Wars Unlimited replay at ${frameLabel}.`;
  const image = `/api/replays/${slug}/og-image?f=${encodeURIComponent(f ?? '')}&t=${encodeURIComponent(t ?? '')}`;

  return {
    title: `${matchup} · KaraBuddy`,
    description,
    openGraph: { title: matchup, description, type: 'website', images: [{ url: image, width: 1200, height: 630 }] },
    twitter: { card: 'summary_large_image', title: matchup, description, images: [image] },
  };
}

export default async function ReplayPage({ params }: PageProps) {
  const { slug } = await params;
  const row = await loadReplay(slug);
  if (!row) notFound();

  // Serialize timestamps for client transport. Owner-first player order
  // (B59-followup) so the sidebar matchup + default title both read
  // "<me> vs <them>" instead of being order-dependent on the raw jsonb
  // key sort.
  const players = orderPlayersOwnerFirst(row.players, row.ownerPlayerId);

  // B107: a curated SAMPLE replay (surfaced publicly on the signed-out home)
  // is anonymized — real handles → "Player N" on the matchup/title here, and
  // the viewer rewrites the board + game log to match (and skips the tag
  // fetch). Order is preserved, so the labels line up with the card.
  const anonymize = isSampleReplaySlug(slug);

  // B112: double-sided replay. Offer the Flip control only to a signed-in viewer
  // who is entitled to the second player's perspective (same predicate the
  // serving endpoint enforces). Never for anonymized samples.
  const session = await auth();
  const viewerUserId = (session?.user as any)?.id ?? null;
  const canFlip = !anonymize && (await canViewAltPerspective(slug, viewerUserId));

  const replay = {
    ...row,
    createdAt: row.createdAt.toISOString(),
    players: anonymize ? anonymizePlayersSummary(players as any[]) : players,
    // Don't leak a real handle through a custom title — fall back to the
    // anonymized "Player 1 vs Player 2" default.
    displayName: anonymize ? null : (row as any).displayName,
  };

  // B71: tags are no longer SSR'd — the viewer fetches them from
  // GET /api/replays/[slug]/tags so the server can scope them to the
  // viewer (own + team-scoped only). SSR'ing all tags would leak other
  // teams' / others' personal comments into the initial HTML.
  return <ReplayViewer replay={replay} initialTags={[]} anonymize={anonymize} canFlip={canFlip} />;
}
